# Generated by Django 5.2 on 2025-04-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playhistory',
            name='play_at',
        ),
        migrations.AddField(
            model_name='playhistory',
            name='play_count',
            field=models.IntegerField(default=0),
        ),
    ]
