# Generated by Django 5.2 on 2025-04-28 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_person_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
