# Generated by Django 5.2 on 2025-05-06 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscoreonsong',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
