# Generated by Django 5.2 on 2025-05-06 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_remove_dynamic_play_count_dynamic_total_play_count_and_more'),
        ('users', '0008_alter_userscoreonsong_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usercollectionsong',
            constraint=models.UniqueConstraint(fields=('user', 'song'), name='unique_user_song_collection'),
        ),
    ]
