# Generated by Django 5.2 on 2025-05-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usercollectionsong_unique_user_song_collection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
