# Generated by Django 5.2 on 2025-05-27 01:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_dynamic_collect_count_and_more'),
        ('users', '0010_delete_uploadedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='playhistory',
            name='play_count',
            field=models.IntegerField(default=0, verbose_name='播放次数'),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.song', verbose_name='歌曲'),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='usercollectionsong',
            name='collect_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='收藏时间'),
        ),
        migrations.AlterField(
            model_name='usercollectionsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.song', verbose_name='歌曲'),
        ),
        migrations.AlterField(
            model_name='usercollectionsong',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userscoreonsong',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='userscoreonsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.song', verbose_name='歌曲'),
        ),
        migrations.AlterField(
            model_name='userscoreonsong',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='playhistory',
            unique_together={('user', 'song')},
        ),
    ]
