# Generated by Django 5.2 on 2025-06-07 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_song_file_path'),
        ('users', '0011_alter_playhistory_play_count_alter_playhistory_song_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userscoreonsong',
            constraint=models.UniqueConstraint(fields=('user', 'song'), name='unique_user_song_score'),
        ),
    ]
