# Generated by Django 5.2 on 2025-04-24 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255, null=True)),
                ('pop', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('list_labels', models.CharField(max_length=1023)),
                ('file_path', models.FileField(null=True, upload_to='songs/')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '歌曲',
                'verbose_name_plural': '歌曲们',
                'ordering': ['-pop', 'name'],
                'indexes': [models.Index(fields=['name'], name='idx_song_name'), models.Index(fields=['artist'], name='idx_song_artist'), models.Index(fields=['pop'], name='idx_song_pop')],
            },
        ),
    ]
