# Generated by Django 5.2 on 2025-04-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='create_time',
            new_name='create_at',
        ),
    ]
