# Generated by Django 5.2 on 2025-04-25 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_create_time_song_create_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-pop', 'name'], 'verbose_name': '歌曲', 'verbose_name_plural': '歌曲'},
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=255, null=True, verbose_name='创作者'),
        ),
        migrations.AlterField(
            model_name='song',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file_path',
            field=models.FileField(null=True, upload_to='songs/', verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='歌曲ID'),
        ),
        migrations.AlterField(
            model_name='song',
            name='list_labels',
            field=models.CharField(max_length=1023, verbose_name='流派'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=255, verbose_name='歌曲'),
        ),
        migrations.AlterField(
            model_name='song',
            name='pop',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='流行度'),
        ),
    ]
