# Generated by Django 5.2 on 2025-04-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_dynamic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamic',
            name='play_count',
        ),
        migrations.AddField(
            model_name='dynamic',
            name='total_play_count',
            field=models.IntegerField(default=0, verbose_name='播放次数'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='collect_count',
            field=models.IntegerField(default=0, verbose_name='收藏次数'),
        ),
    ]
