# Generated by Django 5.2 on 2025-05-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_remove_dynamic_play_count_dynamic_total_play_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamic',
            name='collect_count',
            field=models.IntegerField(default=0, verbose_name='收藏总次数'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='total_play_count',
            field=models.IntegerField(default=0, verbose_name='播放总次数'),
        ),
    ]
