# Generated by Django 5.2 on 2025-05-28 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_dynamic_collect_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file_path',
            field=models.FileField(null=True, upload_to='songs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])], verbose_name='文件路径'),
        ),
    ]
